workspace:
  base: /srv/app
  path: src/github.com/webhippie/templater

pipeline:
  testing:
    image: webhippie/golang:latest
    pull: true
    environment:
      - CGO_ENABLED=0
      - TAGS=
      - GOPATH=/srv/app
    commands:
      - make clean
      - make vet
      - make varcheck
      - make structcheck
      - make unconvert
      - make ineffassign
      - make lint
      - make test
      - make build

  updater:
    image: karalabe/xgo-latest:latest
    environment:
      - CGO_ENABLED=0
      - TAGS=
      - GOPATH=/srv/app
    commands:
      - export PATH=/srv/app/bin:$PATH
      - make publish
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/templater
    tags: [ '${DRONE_TAG##v}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/templater
    tags: [ '${DRONE_BRANCH##release/v}' ]
    when:
      event: [ push ]
      branch: [ release/* ]

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/templater
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  archive:
    image: plugins/s3
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /misc/templater/${DRONE_TAG##v}
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  archive:
    image: plugins/s3
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /misc/templater/${DRONE_TAG##release/v}
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ push ]
      branch: [ release/* ]

  archive:
    image: plugins/s3
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /misc/templater/master
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ push ]
      branch: [ master ]

  github:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  gitter:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
