clone:
  path: github.com/webhippie/templater

build:
  image: golang:1.5

  commands:
    - make deps
    - make build
    - make test
    - make release

publish:
  coverage:
    when:
      branch: master
  github_release:
    api_key: $$GITHUB_APIKEY
    files:
      - dist/*
    when:
      event: tag

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK
    channel: develop
    username: dronehippie

  irc:
    prefix: build
    nick: dronehippie
    channel: webhippie
    server:
      host: chat.freenode.net
      port: 6667

  email:
    from: drone@webhippie.de
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASSWORD
    recipients:
      - thomas@webhippie.de
    when:
      success: false
      failure: true
      change: true
