workspace:
  base: /srv/app
  path: src/github.com/webhippie/templater

pipeline:
  testing:
    image: webhippie/golang:latest
    pull: true
    environment:
      - GOPATH=/srv/app
    commands:
      - make clean
      - make deps
      - make vet
      - make lint
      - make test
      - make build

  updater:
    image: webhippie/golang:latest
    environment:
      - GOPATH=/srv/app
    commands:
      - make publish
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

  # coverage:
  #   image: plugins/coverage

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/templater/master
  #   recursive: true
  #   delete: true
  #   when:
  #     event: push
  #     branch: master

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/templater/$$TAG
  #   recursive: true
  #   delete: true
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/latest/
  #   target: /usr/share/webapps/dl/public_html/templater/latest
  #   recursive: true
  #   delete: true
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/publish/
  #   target: /usr/share/webapps/dl/public_html/templater/updates
  #   recursive: true
  #   delete: false
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # github_release:
  #   image: plugins/github-release
  #   files:
  #     - dist/release/*
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # email:
  #   from: drone@webhippie.de
  #   recipients:
  #     - thomas@webhippie.de
