baseURL = "/"
languageCode = "en-us"
title = "Templater"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "A template processor for environment variables"
  keywords = "template, environment, processor"
