baseURL = "https://webhippie.github.io/templater/"
languageCode = "en-us"
title = "Templater"
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Template processor for env variables"
  keywords = "templates, environment, variables"
